sheetname=Meta-data
column_author1=1
column_author2=2
column_author3=3
column_author4=4
column_author5=5
column_author6=6
column_instrumenttype1=7
column_instrumenttype2=8
column_reseracharea1=9
column_reseracharea2=10
column_reseracharea3=11
column_typeoffile1=12
column_typeoffile2=13
column_software=14
column_instrumenttitle=15
column_notes=16
column_participanttype1=17
column_participanttype2=18
column_language1=19
column_language2=20
column_publication1_type=21
column_publication1_author1=22
column_publication1_author2=23
column_publication1_author3=24
column_publication1_author4=25
column_publication1_author5=26
column_publication1_author6=27
column_publication1_title=28
column_publication1_journal=29
column_publication1_date=30
column_publication1_volume=31
column_publication1_issue_no=32
column_publication1_page_number_from=33
column_publication1_page_number_to=34
column_publication1_doi=35
column_email=36