sheetname=Meta-data
column_author1=1
column_author2=2
column_author3=3
column_author4=4
column_author5=5
column_author6=6
column_instrumenttype1=7
column_instrumenttype2=8
column_reseracharea1=9
column_reseracharea2=10
column_reseracharea3=11
column_typeoffile1=12
column_typeoffile2=13
column_software=14
column_other_software_url=15
column_instrumenttitle=16
column_notes=17
column_participanttype1=18
column_participanttype2=19
column_language1=20
column_language1_2=21
column_language1_3=22
column_language2=23
column_language2_2=24
column_language2_3=25
column_publication1_type=26
column_publication1_author1=27
column_publication1_author2=28
column_publication1_author3=29
column_publication1_author4=30
column_publication1_author5=31
column_publication1_author6=32
column_publication1_title=33
column_publication1_journal=34
column_publication1_date=35
column_publication1_volume=36
column_publication1_issue_no=37
column_publication1_page_number_from=38
column_publication1_page_number_to=39
column_publication1_doi=40
column_email=41